### ISSUE TITLE
Link/Route

### ISSUE THREAD

**Issue by mpaitgt** [jayjscotto/project-3#18]
Master branch is currently rendering Appbar (the navbar) twice - once in index.js and again in App.js. 
The rendering in App.js is needed because it needs the logout function. So we either need eliminate Appbar's rendering in index, or move the logout function from App to index. We will need Laura here because I don't know if that will work!

We also need to put the Link components inside of Appbar, but we cannot render the component in the Link as it does currently: 

```
<Link to="/survey" component={IntakeSurvey}>
```

This causes the component to render inside of the Appbar, which obviously we don't want to happen. We need to call the path inside the Link component and have it render using the Router.

**Comment by jayjscotto** [comment]
This should be fixed
